name: Build & Test

'on':
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: 01 13 * * SAT

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: '>=1.21.1'

      - name: Build
        run: go build -v

      - name: Test
        run: go test ./...

      - name: Run GoReleaser (Ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --snapshot --skip=publish --clean

      - name: Test dry run (Ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: go run cmd/main.go --dry-run --instanceTypes=t3a.xlarge,t3.small
